# Welcome to Stonesteel's blog!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stonesteel's blog
email: stonesteel1023@yahoo.co.jp
description: 
baseurl: ""
url: "https://stonesteel1023.github.io" 
twitter_username: stonesteel1023
github_username:  stonesteel1023

# Build settings
markdown: kramdown
<<<<<<< HEAD
theme: minima
=======
theme: jekyll-theme-minimal
>>>>>>> 71e7f983c9f0d8cba29bfbc0972169ad91f5835d
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
